# Generated by Django 5.2.12 on 2026-03-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectactivity',
            name='activity_type',
            field=models.CharField(choices=[('call', 'Telefon'), ('email', 'Email'), ('meeting', 'Spotkanie')], default='call', max_length=10),
        ),
    ]
