# Generated by Django 5.2.12 on 2026-04-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_prospectclient_registered_client"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerSettlement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("client_registered_at", models.DateTimeField()),
                ("client_paid_plan_started_at", models.DateTimeField(blank=True, null=True)),
                ("client_plan_tier", models.CharField(max_length=16)),
                ("settled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_settlement",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prospect",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settlements",
                        to="sales.prospectclient",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_settlements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "settled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_seller_settlements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-settled_at"],
            },
        ),
    ]
