# Generated by Django 5.2.12 on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="paid_plan_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
