# Generated by Django 5.2.17 on 2026-09-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_email_verified_at_user_pending_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_pending',
            field=models.BooleanField(default=False),
        ),
    ]
