# Generated by Django 5.2.17 on 2026-09-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_googleidentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
