# Generated by Django 5.2.17 on 2026-09-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='closed_display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
