# Generated by Django 5.2.17 on 2026-10-08 20:46

from django.db import migrations, models


def classify_existing_google_identities(apps, schema_editor):
    GoogleIdentity = apps.get_model("accounts", "GoogleIdentity")
    for identity in GoogleIdentity.objects.select_related("user").iterator():
        user = identity.user
        password_is_unusable = not user.password or user.password.startswith("!")
        created_by_google_flow = user.username.startswith("google_") or password_is_unusable
        if not created_by_google_flow:
            GoogleIdentity.objects.filter(pk=identity.pk).update(is_primary=False)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_plan_access_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleidentity',
            name='is_primary',
            field=models.BooleanField(default=True, help_text="Google was selected as this account's sign-in method during registration."),
        ),
        migrations.RunPython(classify_existing_google_identities, migrations.RunPython.noop),
    ]
