# Generated by Django 5.2.17 on 2026-10-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_googleidentity_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='closed_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
