# Generated by Django 5.2.12 on 2026-03-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_organization_content_languages"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="company_type",
            field=models.CharField(
                choices=[
                    ("manufacturing", "Manufacturing"),
                    ("services", "Services"),
                    ("trading", "Trading"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=32,
            ),
        ),
    ]