# Generated by Django 5.2.12 on 2026-03-20 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_organization_company_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="legal_name",
        ),
    ]