# Generated by Django 5.2.12 on 2026-04-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_remove_organization_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='descriptions_by_language',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
