# Generated by Django 5.2.12 on 2026-04-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_organization_descriptions_by_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='primary_language',
            field=models.CharField(choices=[('pl', 'Polski'), ('en', 'English'), ('de', 'Deutsch'), ('es', 'Espanol'), ('it', 'Italiano'), ('fr', 'Francais')], default='pl', max_length=2),
        ),
    ]
