# Generated by Django 5.2.12 on 2026-04-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_alter_organization_primary_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='products_by_language',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
