# Generated by Django 5.2.12 on 2026-09-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descriptions_by_language',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
