# Generated by Django 5.2.17 on 2026-09-06 19:13

from django.db import migrations, models


def preserve_primary_names(apps, schema_editor):
    Product = apps.get_model("companies", "Product")
    for product in Product.objects.using(schema_editor.connection.alias).select_related("organization").iterator(chunk_size=200):
        Product.objects.using(schema_editor.connection.alias).filter(pk=product.pk).update(names_by_language={product.organization.primary_language: product.name})


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_migrate_product_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='names_by_language',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(preserve_primary_names, migrations.RunPython.noop),
    ]
