# Generated by Django 5.2.17 on 2026-09-06 14:20

import apps.billing.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_stripeevent_checkoutattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginvoice',
            name='billing_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='billinginvoice',
            name='document',
            field=models.FileField(storage=apps.billing.storage.private_invoice_storage, upload_to='invoices/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf']), apps.billing.storage.validate_invoice_pdf]),
        ),
        migrations.AlterField(
            model_name='billingpayment',
            name='invoice_document',
            field=models.FileField(blank=True, storage=apps.billing.storage.private_invoice_storage, upload_to='invoices/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf']), apps.billing.storage.validate_invoice_pdf]),
        ),
    ]
