# Generated by Django 5.2.17 on 2026-09-20 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_preserve_legacy_invoices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginvoice',
            name='invoice_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='billinginvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('payment__isnull', False)), fields=('payment',), name='one_invoice_per_stripe_payment'),
        ),
        migrations.AddConstraint(
            model_name='billinginvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('manual_order__isnull', False)), fields=('manual_order',), name='one_invoice_per_manual_order'),
        ),
    ]
