# Generated by Django 5.2.17 on 2026-10-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_alter_billinginvoice_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingsubscription',
            name='termination_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manualplanorder',
            name='termination_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
