# Generated by Django 5.2.17 on 2026-09-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_adminnotification_message_pl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customernotification',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
