# Generated by Django 5.2.17 on 2026-09-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_adminnotification_resolved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='category',
            field=models.CharField(choices=[('customer', 'Customer'), ('plan', 'Plan'), ('payment', 'Payment'), ('invoice', 'Invoice'), ('manual_plan', 'Manual payment'), ('stripe', 'Stripe')], max_length=32),
        ),
        migrations.AlterField(
            model_name='customernotification',
            name='category',
            field=models.CharField(choices=[('customer', 'Customer'), ('plan', 'Plan'), ('payment', 'Payment'), ('invoice', 'Invoice'), ('manual_plan', 'Manual payment'), ('stripe', 'Stripe')], max_length=32),
        ),
    ]
